version: "3"

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - ai-concierge
networks:
  ai-concierge:
    driver: bridge
