version: "3"
services:
  # UI
  ui:
    ports:
      - 3000:3000
    environment:
      STAMP_API_ENDPOINT: "http://localhost:8089"
  # storybook
  storybook:
    ports:
      - 6006:6006

  # Auth
  auth-api:
    ports:
      - "8880:8880"
    environment:
      DB_DRIVER: "mysql"
      DB_ADDR: "root:secret@tcp(auth-db:3306)/aic?charset=utf8mb4&parseTime=True&loc=Local"
      API_PORT: 8880
      REDIS_URL: auth-cache:6379
      AWS_REGION: ap-northeast-1
      AWS_S3_BUCKET: local-bucket
      AWS_SQS_URL: http://sqs.ap-northeast-1.amazonaws.com/123456789012/local-queue
      SSH_KEY: /run/secrets/ssh-key
    secrets:
      - ssh-key

  auth-db:
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aic
      MYSQL_ROOT_PASSWORD: secret

  auth-cache:
    ports:
      - "6379:6379"

secrets:
  ssh-key:
    file: ~/.ssh/ec2.pem
